### ISSUE TITLE
请问Tensor.py里的一些算子比如max算子的grad_fn是怎么计算出来的呢？

### ISSUE THREAD

**Issue by Wanglongzhi2001** [Kaslanarian/PyDyNet#2]
作者您好，我想请问在您写的深度学习框架中，一些算子比如max算子的grad_fn梯度函数是怎么计算的呢？我目前也有想要自己实现一个深度学习框架的想法，看了您的文章和代码收获颇丰，想请问您有没有什么推荐的资料或者有什么建议呢？

**Comment by WeltXing** [comment]
参考`pydynet/tensor.py`的`max`类(line 812), max算子是基础算子, 所以导数是人为定义的。但由于numpy的max函数会考虑axis和keepdims，所以代码和numpy的机制融合了，不是很适合初学者看了。我建议你可以从一元函数的自动微分开始写，然后再考虑多维张量的自动微分，最后再写神经网络。书籍的话，《深度学习进阶——自然语言处理》的第一章简洁且十分契合我们的工作，后面也会提到RNN的实现，我本人也是在看这本书的时候才开始动手写框架（尽管之前有这个想法）。这本书的前作《深度学习入门——基于Python的理论与实现》则更为入门，我当时只参考了里面实现卷积的方法。美中不足的是，书中的框架都是手动微分的。

**Comment by Wanglongzhi2001** [comment]
> 

好的，感谢您的解答
